// Navigation
export const LOAD_NAVIGATION = 'LOAD_NAVIGATION';

// Category
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';


// Theme
export const LOAD_ALL_THEMES = 'LOAD_ALL_THEMES';
export const LOAD_THEMES_BY_CATEGORY = 'LOAD_THEMES_BY_CATEGORY';
export const LOAD_THEME = 'LOAD_THEME';
export const FETCH_THEMES_REQUEST = 'FETCH_THEMES_REQUEST';
export const FETCH_THEMES_SUCCESS = 'FETCH_THEMES_SUCCESS';
export const FETCH_THEMES_FAILURE = 'FETCH_THEMES_FAILURE';

// Activity
export const LOAD_ALL_ACTIVITIES = 'LOAD_ALL_ACTIVITIES';
export const LOAD_ACTIVITIES_BY_CATEGORY = 'LOAD_ACTIVITIES_BY_CATEGORY';
export const LOAD_ACTIVITIES_BY_THEME = 'LOAD_ACTIVITIES_BY_THEME';
export const LOAD_ACTIVITY = 'LOAD_ACTIVITY';
export const FETCH_ACTIVITIES_REQUEST = 'FETCH_ACTIVITIES_REQUEST';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVITIES_FAILURE = 'FETCH_ACTIVITIES_REQUEST';
export const CHANGE_ACTIVITY_DURATION = 'CHANGE_ACTIVITY_DURATION';

// Quote
export const LOAD_ALL_QUOTE = 'LOAD_ALL_QUOTE';
export const LOAD_RANDOM_QUOTE = 'LOAD_RANDOM_QUOTE';

// User
export const LOAD_USER = 'LOAD_USER';
export const ADD_ACTIVITY_LOG = 'ADD_ACTIVITY_LOG';
export const CHANGE_STATS = 'CHANGE_STATS';
